### ISSUE TITLE
Every request to swagger endpoint causes package scan

### ISSUE THREAD

**Issue by silvpol** [smoketurner/dropwizard-swagger#10]
ApiListingResource has no Singleton annotation and in bundle it's being registered via class name rather than an instance. This means it gets instantiated for every request and this check

        if (!initialized) {
            swagger = scan(app, sc);
        }

 is always going to fail and will always call scan method.

**Comment by jplock** [comment]
Unfortunately `ApiListingResource` comes from the `io.swagger` package, but in the case of the bundle, it is being initialized with an instance instead of a class name  -https://github.com/smoketurner/dropwizard-swagger/blob/master/src/main/java/io/federecio/dropwizard/swagger/SwaggerBundle.java#L64

Is this still an issue?

**Comment by silvpol** [comment]
This was changed for 9.2 with this commit https://github.com/smoketurner/dropwizard-swagger/commit/f9c285cd49c599653cc569b614f71089cdc6da23, so this would happen up to and including 9.1
