### ISSUE TITLE
JerseyRootPath should not return uriPrefix

### ISSUE THREAD

**Issue by dllx** [smoketurner/dropwizard-swagger#16]
To accomodate the case when you have a reverse proxy that removes a path prefix before sending the request to the dropwizard service, you can set uriPrefix in the SwaggerBundleConfiguration to this prefix.

This causes the /swagger index template to generate requests to the swagger assets as /prefix/swagger-static/... But it causes also the AssetsBundle to listen at /prefix/swagger-static, which must the be reached via the reverse proxy from the client as /prefix/prefix/swagger-static.

To remedy that, in ConfigurationHelper, the getJerseyRootPath() should not evaluate swaggerBundleConfiguration.getUriPrefix(), but always return the value from the serverFactory. This way, the call to getSwaggerUriPath() for the AssetBundle configuration will be correct, and getUrlPattern() for the index template will also be correct. (It looks like an error that uriPrefix is evaluated in getUrlPattern() as well as getJerseyRootPath() that is called from there, anyway!)

Maybe there are other use cases for uriPrefix that I am not aware of, where this suggested approach won't work?

**Comment by jplock** [comment]
Would you mind submitting a pull request with what you had in mind?  There's a lot of code around setting the proper root path.  I'd love to get rid of all of that if we can, but I don't want to break anything after forking over this module.

**Comment by dllx** [comment]
I don't really understand what you mean in your last two sentences, but anyway here you are...

**Comment by jplock** [comment]
I meant all of this stuff https://github.com/smoketurner/dropwizard-swagger/blob/master/src/main/java/io/federecio/dropwizard/swagger/ConfigurationHelper.java#L44.  Thanks for the PR.

**Comment by dllx** [comment]
For using a reverse proxy, it would be better still to have something like a "common base path" for /swagger and /swagger-static, so that it can be handled in both cases with and without the reverse proxy (in development and production):

both
http://localhost:8080/swagger
http://localhost:8080/swagger-static

and
https://production.com/service-base/swagger
https://production.com/service-base/swagger-static

should work with the same configuration. But that is probably another ticket.

**Comment by esnellman** [comment]
Signature just changed in Dropwizard 1.0

Optional<String>

https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java#L445

**Comment by eciuca** [comment]
Hi, I also have some problems with the impossibility to configure the base url for the explored api. This is my use scenario of the application running on an weblogic instance:

SwaggerPath: http://serverAddress/weblogicContext/dropwizardApplicationContext/swagger
SwaggerStaticPath: http://serverAddress/weblogicContext/swaggerStaticServlet
Configuration of uriPrefix: /weblogicContext
Base URL: /weblogicContext (identical to uriPrefix)

When I click on explore for this json: http://serverAddress/weblogicContext/dropwizardApplicationContext/swagger.json 

I load all the api which is this:
http://serverAddress/weblogicContext/dropwizardApplicationContext/operation1 
http://serverAddress/weblogicContext/dropwizardApplicationContext/operation2
http://serverAddress/weblogicContext/dropwizardApplicationContext/operation3

But because of the base path swagger constructs the call like this:
http://serverAddress/weblogicContext/operation1 

Instead of this:
http://serverAddress/weblogicContext/dropwizardApplicationContext/operation1 

If I would update the uriPrefix to /weblogicContext/dropwizardApplicationContext then theoretically the api calls would be constructed correctly because the base url would be the same as the base url for the operations. But in this case my static content would not be served anymore because the servlet filter will now match the dropwizardContext servlet instead of the swaggerStaticServlet because the dropwizardApplicationServlet is mapped like this /dropwizardApplicationServlet/*.

One solution would be for the baseUrl and uriPrefix to be configured independently or even better, let the code be the same but compute the baseUrl based on the location of the swagger.json

**Comment by jplock** [comment]
A pull request with tests would be welcome.

**Comment by eciuca** [comment]
I am looking now at the implementation of SwaggerResource and SwaggerView. The issue might actually be more close to this one #4 regarding the Assets path because the assets are actually being served from another servlet.

**Comment by jplock** [comment]
I'd be willing to review a pull request if someone wants to fix this with tests.  The prefix handling is a mess in my opinion.

**Comment by eciuca** [comment]
@trasa I dont know if this helps you but I submitted a pull request [1] for the 0.9.x branch at some point to be able to configure the context root. I didn't do it for the master branch though.

I don't know how you would solve this by accessing swagger on an url that is a child context and not on the same level as the application context (other than url rewriting maybe using a reverse proxy)

[1] https://github.com/trasa/dropwizard-swagger/commit/cd237c8fe805efc7ef4b4834bfe646b10cd3d2d7
