### ISSUE TITLE
Update to swagger-core 2.x.x / OpenAPI 3.0

### ISSUE THREAD

**Issue by AndreasHuber-CH** [smoketurner/dropwizard-swagger#170]
Do you have any plans updating dropwizard-swagger to OpenAPI 3.0?
I've seen that swagger-core supports it since version 2.

**Comment by AndreasHuber-CH** [comment]
I wanted to try it out myself and I just realised that swagger-annotations-2.1.1 comes with a whole new set of annotations.
So actually, while I see a couple of nice features in open API 3 I'm not really sure to want to have to go over all existing annotations.
But I'm still curious if its something that will be available in the future, or whether its out of scope of the dropwizard-swagger project.

**Comment by jplock** [comment]
I don’t use this module any longer and would be happy to review any pull requests.

**Comment by AndreasHuber-CH** [comment]
I'll close this issue for now. As swagger-core 2.x.x comes with a new set of annotations we don't persue migrating to it right now

**Comment by chrisrohr** [comment]
@jplock Once we get the existing low hanging fruit updated and a release out, I don't mind taking a stab at this.  One question I had though for your versioning scheme, are you trying to keep in step with the Dropwizard version (i.e. 2.x)?  Since this would be a major change, what would you want the version to be?
