### ISSUE TITLE
urlPrefix not working with dropwizard-swagger 2.1.X

### ISSUE THREAD

**Issue by born-curious** [smoketurner/dropwizard-swagger#320]
urlPrefix is not working with dropwizard-swagger 2.1.X. I checked the code and the openapi object doesn't use this urlPrefix anywhere. 

Due to this the try out button throws 404 method not found as the url path is missing the base path. 

Please have a look at this.

**Comment by TomScarboroughGooday** [comment]
Appears to still be broken in 4.0.0-1

**Comment by sandeepk-veritas** [comment]
Yes, I used both 3.0.0-1 and 4.0.0-1. Both show the exact same issue.

Just to clarify, our application makes use of applicationContextPath and rootPath.

**Comment by sandeepk-veritas** [comment]
@jplock, sorry to mention you directly. But would like your thoughts on this. Is there anything that can be done by us to resolve it?

**Comment by jplock** [comment]
I don’t use this library any longer. I’d be happy to review a PR if someone wanted to address this.

**Comment by RohitPatel1122** [comment]
@born-curious Were you able to fix this ? I am facing same issue. using version 2.1.4-1

**Comment by sandeepk-veritas** [comment]
@RohitPatel1122, @born-curious, @TomScarboroughGooday 
 
Based on my [earlier comment](https://github.com/smoketurner/dropwizard-swagger/issues/317#issuecomment-1589462751) in other thread, it was clear that the issue was because of the deprecation of basePath support in OpenAPI. There had to some implementation which supported populating `servers` list in its place.

Saw that there was a recent PR raised for adding the support for `servers` list to specify one or more base URLs for your API.

https://github.com/smoketurner/dropwizard-swagger/pull/327

So taking that into account, I did some research and found that a commit done earlier removed support for adding base path. 
Earlier the `build` method for class `SwaggerBundleConfiguration` was taking an string input parameter urlPattern which had information about base path and it was removed for reasons unknown and no alternative implementation was made available for supporting base path.

https://github.com/smoketurner/dropwizard-swagger/commit/fc53f0b7721794a522734d6b1e7183586d3abe3e#diff-022f5553f7ee09f652f7dea77da83eec7b8efd0a66a42d8f48dc1048f27925a8L311

Because of this commit `servers` list is not populated anymore.

I tried below code locally on my setup and it seems to be working. Here we are checking if there is any servers list specified via configuration, if none then we are creating one implicitly taking into consideration applicationContextPath, rootPath as well as contextRoot. This change can be added just before return statement in `build` method for class `SwaggerBundleConfiguration`:

```
    if (servers == null || servers.isEmpty()) { // If servers list is not defined explicitly, implicitly create one
      servers =
          Stream.of(new Server().url(("/".equals(contextRoot) ? "" : contextRoot) + urlPattern))
              .collect(Collectors.toList());
    }
```
When calling this method from `run` method of `SwaggerBundle`, we need below changes:

```
    final SwaggerConfiguration oasConfiguration =
        swaggerBundleConfiguration.build(configurationHelper.getUrlPattern());
```

Changes are based on earlier code which used to set base path.

```
config.setBasePath(("/".equals(contextRoot) ? "" : contextRoot) + urlPattern);
```

Can you please try it at your end as well? Suggestions are welcome for any improvements. I will try to raise a PR within this week itself.

**Comment by sandeepk-veritas** [comment]
As I have not received any response after 1 month, I will raise the PR with my changes.

**Comment by alallier** [comment]
@sandeepk-veritas in your above comment we are plagued by the same issue. Your comment summarizes the investigative steps I went down as well.

I don't see any changes in PRs to fix this and more importanly the stale bot keeps closing all related issues regarding this.

This completely breaks all use cases that don't run on a `/` context path.

**Comment by oscarnalin** [comment]
Is there any updates on this? `rootPath` is still breaking the "Try it out" button for swagger
