### ISSUE TITLE
Swagger Assets Path

### ISSUE THREAD

**Issue by edwardsb** [smoketurner/dropwizard-swagger#4]
Would it be useful to provide a configuration value to define a different path to swagger assets in case we would want to return our own custom swagger themed documents page, instead of the default swagger assets?

I am thinking it would be a configuration value instead of being defined in Constants.java.

If this is already a possibility please correct me, but it doesn't seem to be so. Only other alternative is to fork the project and supply our own swagger assets in the static directory.

**Comment by jplock** [comment]
Mind submitting a pull request?

**Comment by jplock** [comment]
I just removed `Constants.java` in #14  as part of some cleanups.  I think this could possibly be exposed via the `SwaggerBundleConfiguration` though.

**Comment by jeffpeiyt** [comment]
+1, how to customize the logos etc?  if we can put our dist folder ( with the html/css etc) to some location?

**Comment by jennifergarcia** [comment]
There are two ways to do this that provide different functionality:

1) Just override the location of the template file and you can customize how you would like and put this in the configuration object as suggested.  This would limit any template changes to what is available in SwaggerUI
2) Modify the project such that you can define a custom view object which implements the SwaggerView.  This would allow you to add additional flags to your template beyond what is available in SwaggerUI.

I need to customize in order to add some custom auth code and can't do that without modifying the template and am considering creating a pull request to allow customization of the template file.  Do you guys have any input on what the better route would be to go?

**Comment by sebastienvermeille** [comment]
Hi ! First of all thank you very much for this great dropwizard swagger integration (the old dep was unusable and I have lost a lot of time for it).

As a temporary work around here is how I manage it :

I created in /resources/ a folder called swagger containing swagger-ui.

Then in my DropwizardApplication main class : 
``
    public void initialize(Bootstrap<VinturoConfiguration> bootstrap) {

             bootstrap.addBundle(new AssetsBundle("/swagger", "/swagger", null, "swagger"));
``
And then simply adapt the url to load in your swagger-ui installation.

But I approve this feature request. We should have the choice to use a separate swagger-ui maybe simply create another maven dep for swagger-ui ?
